### ISSUE TITLE
'Snookey' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by lucas-membrane** [IOnlyPlayAsDrift/Snookey2#5]
I've tried all of the fixes listed on the site and none of them seem to work. I've tried reinstalling snookey and the same problem still occurs. What else can I do to fix this?

(When I try running a snookey command, it gives me that error even though the installation process is complete.)
[Snookeynowork.txt](https://github.com/IOnlyPlayAsDrift/Snookey2/files/4963748/Snookeynowork.txt)

**Comment by IOnlyPlayAsDrift** [comment]
I’m sorry you’re having this issue, please join the Discord for support problems:  
https://discord.gg/BmYs5Uv  
Thank you for understanding!
